---
name: RC-009 – Visibility
description: 水面→壁の可視性（遮蔽物）による減衰の近似
title: "[RC-009] 水面→壁の可視性（遮蔽物）による減衰の簡易対応"
labels: ["feature", "lighting"]
body:
  - type: checkboxes
    id: tasks
    attributes:
      label: タスク / Tasks
      options:
        - label: メインライトのシャドウ方向で簡易可視性評価
        - label: 破綻ケースのREADME明記
  - type: checkboxes
    id: ac
    attributes:
      label: 受け入れ基準 / Acceptance Criteria
      options:
        - label: 遮蔽物がある部分の輝度が下がる
